#include "Items.h"
#include "Shop.h"
#include "Chat.h"




Shop::shop* Shop::currentShop;
// add an update at the bottem of logic for any new shops
Shop::shop
	Shop::generalShopCurrent
	{
		Shop::SHOP_GENERAL,
		Items::goldRing,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		//current stock
		10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
		//default stock
		10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	},
	Shop::generalShopDefault
	{
		Shop::SHOP_NONE,
		Items::goldRing,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		//current stock
		10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
		//default stock
		10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	},
	Shop::barShop
	{
		Shop::SHOP_BAR,
		Items::bronzeBar,
		Items::ironBar,
		Items::steelBar,
		Items::mithrilBar,
		Items::adamantiumBar,
		Items::runeBar,
		Items::silverBar,
		Items::goldBar,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		//current stock
		0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
		//default stock
		0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	},
	Shop::oreShop
	{
		Shop::SHOP_ORE,
		Items::copperOre,
		Items::tinOre,
		Items::ironOre,
		Items::coalOre,
		Items::mithrilOre,
		Items::adamantiteOre,
		Items::runiteOre,
		Items::silverOre,
		Items::goldOre,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		//current stock
		0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
		//default stock
		0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	},
	Shop::icecreamShop
	{
		Shop::SHOP_ICECREAM,
		Items::chocolateIcecream,
		Items::strawberryIcecream,
		Items::peachIcecream,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		Items::empty,
		//current stock
		10,10,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
		//default stock
		10,10,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
	};












Shop::shop Shop::getCurrentShop()
{
	return *Shop::currentShop;
}
